### ISSUE TITLE
Window resizing bug

### ISSUE THREAD

**Issue by zoalst** [metasyn/dreda#9]
If the window is resized the 3D rendering gets stretched or smooshed. I'm going to look into using [THREEx.WindowResize](https://github.com/jeromeetienne/threex.windowresize) to fix this.
![screenshot from 2015-04-28 12 22 44](https://cloud.githubusercontent.com/assets/7537243/7378755/bc49e74e-eda4-11e4-993c-7cd4a3416beb.png)

**Comment by metasyn** [comment]
I had window resize in there before but it was fucking things up so I yanked it out. Rather than adding in something super crazy dynamic, we just need to change the css.

In `./css/stylish.css', under the`#data-canvas` - we can change that width and height to whatever. The reason that it is getting all fucked up when you move it around is because those values are 100% of the div, which is being resized, whereas the aspect in the initalization is set to that when it first renders the scene.

I think that means we just need  an updateAspect function in the animate or update function
